<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pwpeg</string>
	</array>
	<key>name</key>
	<string>PwPEG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#codeblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#label</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#predicate</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#actionline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#regexp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rulename</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bckstring</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_simple</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>actionblock</key>
		<dict>
			<key>begin</key>
			<string>^(?=(\s*).*)-&gt;\s*$</string>
			<key>end</key>
			<string>^(?!(\2\s+|\s*$))</string>
			<key>name</key>
			<string>markup.other</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>actionline</key>
		<dict>
			<key>begin</key>
			<string>(?=-&gt;)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.other</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>bckstring</key>
		<dict>
			<key>match</key>
			<string>\\[^\s]+</string>
			<key>name</key>
			<string>string.other.vld</string>
		</dict>
		<key>codeblock</key>
		<dict>
			<key>begin</key>
			<string>%%</string>
			<key>end</key>
			<string>%%</string>
			<key>name</key>
			<string>markup.other</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.pwpeg</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.pwpeg</string>
		</dict>
		<key>indentedblock</key>
		<dict>
			<key>begin</key>
			<string>(\s+)(?=[^\s])</string>
			<key>end</key>
			<string>(?!(\1|\s*$))</string>
			<key>name</key>
			<string>markup.other</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(set|and|or|as|if|not|else|elif|endif|in|is|default)\b</string>
			<key>name</key>
			<string>keyword.other.pwpeg</string>
		</dict>
		<key>label</key>
		<dict>
			<key>match</key>
			<string>\w+\s*:</string>
			<key>name</key>
			<string>entity.name.pwpeg</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(0x|0o)?[0-9]+(\.[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.pwpeg</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>(\?|\||\*|\+|!|&amp;)</string>
			<key>name</key>
			<string>keyword.control.vld</string>
		</dict>
		<key>predicate</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>markup.other</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>regexp</key>
		<dict>
			<key>begin</key>
			<string>/</string>
			<key>end</key>
			<string>/[a-z]*</string>
			<key>name</key>
			<string>string.regexp.pwpeg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<key>rulename</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z0-9_]*\s*(skip\s+\w+\s*)?=</string>
			<key>name</key>
			<string>variable.other.vld</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(["'])</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.quoted.pwpeg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pwpeg</string>
	<key>uuid</key>
	<string>3814d5f3-a8c7-4590-89cc-b9e343b7aef6</string>
</dict>
</plist>
